services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: taskiqaiopg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskiqaiopg"]
      interval: 3s
      timeout: 1s
      retries: 5
  redis:
    image: redis:7
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 1s
      retries: 5
