name: Linters and tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: postgres
          password: postgres
          database: taskiqaiopg
        id: postgres
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.13"
          enable-cache: true
          cache-suffix: "${{ hashFiles('uv.lock') }}"
      - name: Install Dependencies
        if: steps.setup-uv.outputs.cache-hit != 'true'
        run: |
          uv sync --all-extras
      - name: Test
        run: uv run pytest
