name: Linters and tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: postgres
          password: postgres
          database: taskiqaiopg
        id: postgres
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.13"
          enable-cache: true
          cache-suffix: ${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        if: steps.setup-uv.outputs.cache-hit != 'true'
        run: uv sync --all-extras
      - name: Test
        run: uv run pytest
